/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.ioc.example;

import io.javalin.Javalin;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import spring.ioc.example.Consumer.AnotherService;
import spring.ioc.example.Consumer.BarService;
import spring.ioc.example.Consumer.Config;
import spring.ioc.example.Consumer.FooService;

public class App {

	static void startWebServer() {

		Javalin.create()
			.defaultContentType("application/json")
			.requestLogger((ctx, timeMs) ->
				System.out.println(ctx.method() + " " + ctx.path() + " took " + timeMs + " ms")
			)
			.get("/health-check", ctx -> ctx.result("{ \"message\": \"I'm ok\" }\n"))
			.start(80);
	}

	static void startWorkers() {
		AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
		applicationContext.register(Config.class);
		applicationContext.refresh();

		FooService fooService = applicationContext.getBean(FooService.class);
		BarService barService = applicationContext.getBean(BarService.class);
		AnotherService anotherService = applicationContext.getBean(AnotherService.class);
		barService.start();
		fooService.start();
		anotherService.start();
	}


	public static void main(String[] args) {
		startWorkers();
		startWebServer();

		Runtime rt = Runtime.getRuntime();
		System.out.println("cpu cores: " + rt.availableProcessors());
		System.out.println("total memory: " + rt.totalMemory());
		System.out.println("free memory: " + rt.freeMemory());
	}
}
