/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.ioc.example;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import spring.ioc.example.Consumer.AnotherService;
import spring.ioc.example.Consumer.BarService;
import spring.ioc.example.Consumer.Config;
import spring.ioc.example.Consumer.FooService;
import static spark.Spark.get;
import static spark.Spark.port;

public class App {

    static void startWebServer() {

        port(80);
        get("/health-check", "application/json", (req, res) -> "{ \"message\": \"I'm ok\" }\n");
    }

    static void startWorkers() {
        AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
        applicationContext.register(Config.class);
        applicationContext.refresh();

        FooService fooService = applicationContext.getBean(FooService.class);
        BarService barService = applicationContext.getBean(BarService.class);
        AnotherService anotherService = applicationContext.getBean(AnotherService.class);
        barService.start();
        fooService.start();
        anotherService.start();
    }


    public static void main(String[] args) {
      startWebServer();
    	startWorkers();
    }
}
